Error (10028): Can't resolve multiple constant drivers for net "board_we" at gamelogic.v(189)
Error (10029): Constant driver at gamelogic.v(267)
Error (10028): Can't resolve multiple constant drivers for net "board_wx[3]" at gamelogic.v(189)
Error (10028): Can't resolve multiple constant drivers for net "board_wx[2]" at gamelogic.v(189)
Error (10028): Can't resolve multiple constant drivers for net "board_wx[1]" at gamelogic.v(189)
Error (10028): Can't resolve multiple constant drivers for net "board_wx[0]" at gamelogic.v(189)
Error (10028): Can't resolve multiple constant drivers for net "board_wy[4]" at gamelogic.v(189)
Error (10028): Can't resolve multiple constant drivers for net "board_wy[3]" at gamelogic.v(189)
Error (10028): Can't resolve multiple constant drivers for net "board_wy[2]" at gamelogic.v(189)
Error (10028): Can't resolve multiple constant drivers for net "board_wy[1]" at gamelogic.v(189)
Error (10028): Can't resolve multiple constant drivers for net "board_wy[0]" at gamelogic.v(189)
Error (10028): Can't resolve multiple constant drivers for net "board_wdata" at gamelogic.v(189)
Error (12152): Can't elaborate user hierarchy "gamelogic:GAME"
